# Generated by Django 5.1.1 on 2024-10-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='orgin_country',
            new_name='origin_country',
        ),
    ]
